eshop/urls.py
from django.conf.urls import url
from . import views, auth_views
from .customer import Search, Buy, CustomerRemittanceManager
from .seller import ShopManager, GoodsManager, ShopRemittanceManager
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    #1.基本界面 ****************************************************************************

    url(r'^$', views.index, name='index'),
    url(r'^shop_list$', views.shop_list, name='shop_list'),
    url(r'^homepage$', views.homepage, name = 'homepage'),
    url(r'^shop/([1-9][0-9]*)$', views.shop, name='shop'),
    url(r'^shop/([1-9][0-9]*)/goods/([1-9][0-9]*)$', views.goods, name='goods'),
    url(r'^shop_homepage/([1-9][0-9]*)$', views.shop_homepage, name = 'shop_homepage'),
    url(r'^shop_homepage/([1-9][0-9]*)/shop_goods/([1-9][0-9]*)$', views.goods, name="goods"),

    #2.用户管理 ****************************************************************************

    url(r'^login$', auth_views.login, name='login'),
    url(r'^authenticate$', auth_views.authenticate, name='authenticate'),
    url(r'^signup$', auth_views.signup, name='signup'),
    url(r'^signup/submit$', auth_views.signup_submit, name='signup-submit'),
    url(r'^logout$', auth_views.logout, name='logout'),
    url(r'^homepage/user_info$', auth_views.user_info, name='user_info'),
    url(r'^homepage/user_info/change_user_info$', auth_views.change_user_info, name='change_user_info'),
    url(r'^homepage/user_info/save_user_info$', auth_views.save_user_info, name='save_user_info'),

    #3.消费者 ****************************************************************************

    #消费者-搜索相关
    url(r'^search$', Search.search,
        name='search'),

    #消费者-购物相关
    #直接购买
    url(r'^shop/([1-9][0-9]*)/goods/([1-9][0-9]*)/buy_directly$', Buy.buy_directly,
        name='buy_directly'),
    #购物车界面
    url(r'^shoppingcart$', Buy.shoppingcart,
        name='shoppingcart'),
    #从购物车移除物品
    url(r'^shoppingcart/removefromcart/([1-9][0-9]*)$', Buy.removefromcart,
        name="removefromcart"),
    #清空购物车
    url(r'^shoppingcart/removeall/([1-9][0-9]*)$', Buy.removeall,
        name="removeall"),
    #购物车全部购买
    url(r'^shoppingcart/buyall/$', Buy.buyall,
        name="buyall"),
    #将商品添加到购物车
    url(r'^shop/([1-9][0-9]*)/goods/([1-9][0-9]*)/addtocart$', Buy.addtocart,
        name='addtocart'),

    #消费者－订单相关
    #所有订单
    url(r'^homepage/remittances$', CustomerRemittanceManager.remittances,
        name='remittances'),
    #订单详情
    url(r'^remittance/([1-9][0-9]*)$', CustomerRemittanceManager.remittance,
        name='remittance'),
    #店铺打包创建订单，通过购物车
    url(r'^create_remittance_shop/([1-9][0-9]*)$', CustomerRemittanceManager.create_remittance_shop,
        name='create_remittance_shop'),
    #通过商品创建订单，通过直接购买按钮
    url(r'^create_remittance_goods/([1-9][0-9]*)$', CustomerRemittanceManager.create_remittance_goods,
        name='create_remittance_goods'),
    #确认收货
    url(r'^remittance/([1-9][0-9]*)/customer_confirm_remittance$', CustomerRemittanceManager.customer_confirm_remittance,
        name='customer_confirm_remittance'),
    #评价订单
    url(r'^remittance/([1-9][0-9]*)/evaluate_remittance$', CustomerRemittanceManager.evaluate_remittance,
        name='evaluate_remittance'),
    #存储订单评价信息
    url(r'^remittance/([1-9][0-9]*)/customer_evaluate_remittance$', CustomerRemittanceManager.customer_evaluate_remittance,
        name='customer_evaluate_remittance'),

    #4.销售者 ****************************************************************************

    #店铺列表
    url(r'^homepage/my_shop$', ShopManager.my_shop,
        name='my_shop'),
    #创建店铺
    url(r'^create_shop$', ShopManager.create_shop,
        name='create_shop'),
    #店铺主页
    url(r'shop_homepage/([1-9][0-9]*)$', ShopManager.shop_homepage,
        name='shop_homepage'),
    #店铺信息
    url(r'^shop_homepage/([1-9][0-9]*)/shop_info$', ShopManager.shop_info,
        name='shop_info'),
    #修改店铺信息
    url(r'^shop_homepage/([1-9][0-9]*)/shop_info/change_shop_info$', ShopManager.change_shop_info,
        name='change_shop_info'),
    #存储店铺信息
    url(r'^shop_homepage/([1-9][0-9]*)/shop_info/save_shop_info$', ShopManager.save_shop_info,
        name='save_shop_info'),
    #店铺商品列表
    url(r'^shop_homepage/([1-9][0-9]*)/shop_goods$', ShopManager.shop_goods,
        name='shop_goods'),
    #创建商品
    url(r'^shop_homepage/([1-9][0-9]*)/create_goods$', GoodsManager.create_goods,
        name='create_goods'),
    #修改商品信息
    url(r'^shop_homepage/([1-9][0-9]*)/shop_goods/change_goods_info/([1-9][0-9]*)$', GoodsManager.change_goods_info,
        name='change_goods_info'),
    #保存商品信息
    url(r'^shop_homepage/([1-9][0-9]*)/shop_goods/save_goods_info/([1-9][0-9]*)$', GoodsManager.save_goods_info,
        name='save_goods_info'),
    #店铺订单列表
    url(r'^shop_homepage/([1-9][0-9]*)/shop_remittances$', ShopRemittanceManager.shop_remittances,
        name='shop_remittances'),
    #店铺订单详情页
    url(r'^shop_homepage/([1-9][0-9]*)/shop_remittance/([1-9][0-9]*)$', ShopRemittanceManager.shop_remittance,
        name='shop_remittance'),
    #订单发货
    url(r'^shop_homepage/([1-9][0-9]*)/shop_remittance/([1-9][0-9]*)/shop_confirm_remittance$', ShopRemittanceManager.shop_confirm_remittance,
        name='shop_confirm_remittance'),

    #5.管理者 ****************************************************************************

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('eshop.urls')),
]

eshop/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

class Webuser(models.Model):
    ori_user = models.OneToOneField('auth.User', related_name='real_user', related_query_name='real_users')
    is_owner = models.BooleanField()
    nickname = models.CharField(max_length=20)
    gender = models.BooleanField()
    age = models.IntegerField()
    photo = models.ImageField(blank = True, upload_to = 'userphoto')
    email = models.EmailField(blank = True)

class Shop(models.Model):
    owner = models.ForeignKey('Webuser',
            related_name = 'shops',
            related_query_name = 'shop')
    name = models.CharField(max_length=20)
    introduction = models.TextField()
    photo = models.ImageField(blank = True, upload_to = 'shopphoto')
    address = models.CharField(max_length = 255)
    created_at = models.DateTimeField(default = timezone.now)
    sales = models.PositiveIntegerField(default = 0)

class ShoppingCartItem(models.Model):
    owner = models.ForeignKey('Webuser',
        related_name = 'shoppingCart',
        related_query_name = 'shoppingCartItem')
    goods = models.ForeignKey('Goods',
            related_name = 'shoppingcart_items')
    number = models.PositiveIntegerField()

class Remittance(models.Model):
    owner = models.ForeignKey('Webuser',
            related_name = 'remittances',
            related_query_name = 'remittance')
    shop = models.ForeignKey('Shop',
            related_name = 'remittances',
            related_query_name = 'remittance')
    STATUS_CHOICE = (
            ('c', '已下单'),
            ('t', '配送中'),
            ('r', '已收货'),
            ('e', '已评价')
        )
    status = models.CharField(max_length = 1, choices=STATUS_CHOICE, default="c")
    address = models.CharField(max_length = 255)
    payment_choices = (
            (0, '在线支付'),
            (1, '货到付款'),
        )
    payment = models.IntegerField(choices = payment_choices)
    phone = models.CharField(max_length = 20)
    message = models.CharField(max_length = 255)
    price = models.DecimalField(max_digits = 7, decimal_places = 2)
    created_at = models.DateTimeField(default = timezone.now)

class RemittanceItem(models.Model):
    remittance = models.ForeignKey('Remittance',
            related_name = 'remittance_items',
            related_query_name = 'remittance_item')
    goods = models.ForeignKey('Goods',
            related_name = 'remittance_item')
    number = models.PositiveIntegerField()

class Type(models.Model):
    name = models.CharField(max_length = 20)

class Goods(models.Model):
    shop = models.ForeignKey('Shop',
            related_name = 'goods',
            related_query_name = 'shop_goods')
    name = models.CharField(max_length = 20)
    price = models.DecimalField(max_digits = 7, decimal_places = 2)
    introduction = models.TextField()
    total_score = models.FloatField(default=0)
    score_num = models.IntegerField(default=0)
    score = models.DecimalField(max_digits = 2, decimal_places = 1, default = 0)
    goods_type = models.ForeignKey('Type',
            related_name = 'type_goods',
            related_query_name = 'type_goods',
            null = True)
    keywords = models.ManyToManyField('Keyword',
            related_name = 'keyword_goods',
            related_query_name = 'keyword_goods')
    sales = models.PositiveIntegerField(default = 0)

class Keyword(models.Model):
    name = models.CharField(max_length = 20)

class GoodsImage(models.Model):
    image = models.ImageField(upload_to = 'goodsphoto')
    goods = models.ForeignKey('Goods',
            related_name = 'goods_images',
            related_query_name = 'goods_image')

class Comment(models.Model):
    item = models.OneToOneField('RemittanceItem',
            related_name = 'comment',
            related_query_name = 'comments')
    author = models.ForeignKey('Webuser',
            related_name = 'comment',
            related_query_name = 'comments')
    content = models.TextField()
    score = models.IntegerField()
    created_at = models.DateTimeField(default = timezone.now)

eshop/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.contrib import messages
from .models import Shop, Goods, Webuser, RemittanceItem

#主页
def index(request):
    goodss = Goods.objects.order_by('-sales')
    return render(request, 'base/index.html', {'goodss': goodss})

#商店列表
def shop_list(request):
    shops = Shop.objects.order_by('-sales')
    return render(request, 'base/shop_list.html', {'shops': shops})

#店铺界面
def shop(request, shop_id):
    shop = get_object_or_404(Shop, pk=shop_id)
    return render(request, 'base/shop.html', {'shop': shop})

#商品界面
def goods(request, shop_id, goods_id):
    goods = get_object_or_404(Goods, pk=goods_id)
    finished_items = RemittanceItem.objects.filter(goods = goods, remittance__status = 'e')
    return render(request, 'base/goods.html', {'goods': goods, 'finished_items': finished_items})

#个人主页
def homepage(request):
    real_user = get_object_or_404(Webuser, pk = request.user.real_user.id)
    return render(request, 'base/user_info.html', {'real_user': real_user})

#商店主页
def shop_homepage(request, shop_id):
    shop = get_object_or_404(Shop, pk = shop_id)
    return render(request, 'seller/shop_info.html', {'shop': shop})

eshop/templates/customer/change_user_info.html
{% extends 'customer/homepage.html' %}
{% load bootstrap3 %}
{% block homepage_content %}
<h2>个人信息</h2>

<form method="post" enctype="multipart/form-data" action="{% url 'save_user_info' %}" style="float:left">
    <ul class="list-group">
        <li class="list-group-item clearfix">
            <div class="word-wrap">
                {% bootstrap_icon 'user' %}{{ user.username }}
            </div>
        </li>
        <li class="list-group-item clearfix">
            <div class="word-wrap">
                <table class="table" style="margin-bottom:0">
                    <tbody>
                        <tr>
                            <td style="border-top:0">
                                {% csrf_token %}
                                <div class="form-group" style="display:inline-block;margin-bottom:0">
                                    <label for="nickname" style="float:left;padding-top:7px">昵称：
                                    </label>
                                    <input type="text" value = "{{ user.username }}" id="nickname" name="nickname" class="form-control" " required style="float:left;width:400px" />
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="form-group" style="display:inline-block;margin-bottom:0">
                                    <label for="gender" style="float:left;padding-top:7px">性别：
                                    </label>
                                    <label><input checked="true" name="gender" type="radio" value="0" />&nbsp男&nbsp&nbsp</label>
                                    <label><input name="gender" type="radio" value="1" />&nbsp女 </label> 
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="form-group" style="display:inline-block;margin-bottom:0">
                                    <label for="age" style="float:left;padding-top:7px" >年龄：
                                    </label>
                                    <input type="number" id="age" name="age" class="form-control" value="{{ user.real_user.age }}" min="1" max="150" required style="float:left;width:400px" />
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="form-group" style="display:inline-block;margin-bottom:0">
                                    <label for="email" style="float:left;padding-top:7px">邮箱：
                                    </label>
                                    <input type="email" value="{{ user.real_user.email }}" id="email" name="email" class="form-control" placeholder="tips: 填假的我们也不会去验证啦……" required style="float:left;width:400px" />
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                {% csrf_token %}
                                <label for="photo" style="float:left;padding-top:7px">头像：
                                </label>
                                <input type="file" id="photo" name="photo" style="float:left;width:400px" />
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </li>
        <li class="list-group-item clearfix">
            <div class="pull-right">
                <button type="submit" class="btn btn-primary">确认</button>
            </div>
        </li>
    </ul>
</form>
{% endblock %}

eshop/templates/customer/create_remittance.html
{% extends 'base/base.html' %}
{% load bootstrap3 %}
{% block content %}

<h3>新订单</h3>
<table class="table">
    <tbody>
        {% for item in user.real_user.shoppingCart.all %}
        <tr>
            <td>
            <a href = "{% url 'goods' item.goods.shop.id item.goods.id %}">
            {{ item.goods.name }}</a>
            </td>
            <td>
            <p>数量：{{ item.number }}</p>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div>
    <form method="post" action="{% url 'remittance' shop.id %}">
    {% csrf_token %}
    <div class="form-group">
        <label for="phone">联系方式
        </label>
        <input type="text" id="phone" name="phone" class="form-control" placeholder="手机或其他联系方式" required />
    </div>
    <div class="form-group">
        <label for="address">送货地址
        </label>
        <input type="text" pattern="[1-9][0-9]*" id="address" name="address" class="form-control" placeholder="请输入精确的地址以方便派送" required />
    </div>
    <div class="form-group">
        <label for="message">留言
        </label>
        <input type="text" id="message" name="message" class="form-control" placeholder="有特殊的要求可在此处给卖家留言" required />
    </div>
    {% buttons submit='提交' %}{% endbuttons %}
    </form>
</div>

<form method="post" action="{% url 'pay' remittance.id %}">{% csrf_token %}
    <button type="submit" class="btn btn-primary" title="点击此处前往付款界面">
    付款
    </button>
</form>
{% include 'base/messages.html' %}
{% endblock %}

eshop/templates/customer/create_remittance_directly.html
{% extends 'base/base.html' %}
{% load bootstrap3 %}
{% block content %}

<h3>新订单</h3>
<h5>店铺 {{new_remittance.shop.name}}</h5>
<table class="table">
    <tbody>
        <tr>
            <td>
            <a href = "{% url 'goods' item.goods.shop.id item.goods.id %}">
            {{ item.goods.name }}</a>
            </td>
            <td>
            <p>数量：{{ item.number }}</p>
            </td>
            <td>
            <p>价格：¥{{ item.goods.price}} * {{item.number}}</p>
            </td>
        </tr>
        <tr>
        <td></td><td></td><td>总价：¥{{new_remittance.price}}</td>
        </tr>
    </tbody>
</table>
<div>
    <form method="post" action="{% url 'create_remittance_goods' new_remittance.id %}">
    {% csrf_token %}
    <div class="form-group">
        <label for="phone">联系方式
        </label>
        <input type="text" id="phone" name="phone" class="form-control" placeholder="手机或其他联系方式" required />
    </div>
    <div class="form-group">
        <label for="address">送货地址
        </label>
        <input type="text" id="address" name="address" class="form-control" placeholder="请输入精确的地址以方便派送" required />
    </div>
    <div class="form-group">
        <label for="message">留言
        </label>
        <input type="text" id="message" name="message" class="form-control" placeholder="有特殊的要求可在此处给卖家留言" required />
    </div>
    <label><input checked="true" name="payment" type="radio" value="0" />在线支付 </label>
    <label><input name="payment" type="radio" value="1" />货到付款 </label> 
    <br/>
    <button type="submit" class="btn btn-primary">提交订单</button>
    </form>
    <hr>
</div>

{% include 'base/messages.html' %}
{% endblock %}

eshop/templates/customer/create_remittance_fromcart.html
{% extends 'base/base.html' %}
{% load bootstrap3 %}
{% block content %}

<h3>新订单</h3>
{% for group in order_groups %}
<h5>店铺 {{group.shop.name}}</h5>
<table class="table">
    <tbody>
        {% for item in user.real_user.shoppingCart.all %}
        {% if item.goods.shop == group.shop %}
        <tr>
            <td>
            <a href = "{% url 'goods' item.goods.shop.id item.goods.id %}">
            {{ item.goods.name }}</a>
            </td>
            <td>
            <p>数量：{{ item.number }}</p>
            </td>
            <td>
            <p>价格：¥{{ item.goods.price}} * {{item.number}}</p>
            </td>
        </tr>
        {% endif %}
        {% endfor %}
        <tr>
        <td></td><td></td><td>总价：¥{{group.price}}</td>
        </tr>
    </tbody>
</table>
<div>
    <form method="post" action="{% url 'create_remittance_shop' group.shop.id %}">
    {% csrf_token %}
    <div class="form-group">
        <label for="phone">联系方式
        </label>
        <input type="text" id="phone" name="phone" class="form-control" placeholder="手机或其他联系方式" required />
    </div>
    <div class="form-group">
        <label for="address">送货地址
        </label>
        <input type="text" id="address" name="address" class="form-control" placeholder="请输入精确的地址以方便派送" required />
    </div>
    <div class="form-group">
        <label for="message">留言
        </label>
        <input type="text" id="message" name="message" class="form-control" placeholder="有特殊的要求可在此处给卖家留言" required />
    </div>
    <button type="submit" class="btn btn-primary">提交订单</button>
    </form>
    <hr>
</div>
{% endfor %}

{% include 'base/messages.html' %}
{% endblock %}

eshop/templates/customer/evaluate_remittance.html
{% extends 'customer/homepage.html' %} {% load bootstrap3 %} {% block homepage_content %}
<h2>我的订单</h2>
<table class="table">
    <tbody>
        <tr>
            <td>
                <form method="post" action="{% url 'customer_evaluate_remittance' remittance.id %}">
                    {% csrf_token %}
                    <li class="list-group-item">{{ remittance.remittance_items.count }}种商品</li>
                    {% for item in remittance.remittance_items.all %}
                    <li class="list-group-item clearfix">
                        <div class="word-wrap">商品名：{{ item.goods.name }}</div>
                        <div class="word-wrap">总价格：{{ item.goods.price }}</div>
                        <div class="word-wrap">商品类型：{% for key in item.goods.keywords.all|dictsort:"name" %}[ {{ key.name }} ] {% endfor %}</div>
                        <div class="word-wrap"><p>创建评价：</p>
                            <p style="float:left;padding-top:8px">评分(1~5)</p>
                            <input type="number" id="score-{{item.id}}" name="score-{{item.id}}" min=0 max=5 class="form-control" placeholder="please score me..." required style="float:left;width:95.1%" />
                            <p style="float:left;padding-top:8px">评价内容</p>
                            <textarea id="evaluation-{{item.id}}" name="evaluation-{{item.id}}" class="form-control" required style="width:100%"></textarea>
                        </div>
                    </li>
                    {% endfor %}
                    <li class="list-group-item" style="height:56px" ><button type="submit" class="btn btn-primary pull-right">确认评价</button></li>
                </form>
            </td>
        </tr>
    </tbody>
</table>
{% endblock %}

eshop/templates/customer/evaluated_remittances.html
{% extends 'customer/homepage.html' %} {% load bootstrap3 %} {% block homepage_content %}
<h2>我的订单</h2>
<table class="table">
    <tbody>
        {% for remittance in real_user.remittances.all %}
        {% if remittance.status == 'e' %}
        <tr>
            <td>
                <li class="list-group-item">{{ remittance.remittance_items.count }}种商品</li>
                {% for item in remittance.remittance_items.all %}
                <li class="list-group-item clearfix">
                    <div class="word-wrap">商品名：{{ item.goods.name }}</div>
                    <div class="word-wrap">总价格：{{ item.goods.price }}</div>
                    <div class="word-wrap">商品类型：{% for key in item.goods.keywords.all|dictsort:"name" %}[ {{ key.name }} ] {% endfor %}</div>
                    <div class="word-wrap">我的评分：{{ item.comment.score }}
                    </div>
                    <div class="word-wrap">我的评价：{{ item.comment.content }}
                    </div>
                </li>
                {% endfor %}
            </td>
        </tr>
        {% endif %}
        {% endfor %}
    </tbody>
</table>
{% endblock %}

eshop/templates/customer/homepage.html
{% extends 'base/homepage_base.html' %} {% load bootstrap3 %} {% block sidebar %}
<h4>买家中心</h4>
<ul class="nav nav-sidebar">
    <li><a href="{% url 'user_info' %}">个人信息</a></li>
    <li><a href="{% url 'remittances' %}">我的订单</a></li>
</ul>
<h4>卖家中心</h4>
<ul class="nav nav-sidebar">
    <li><a href="{% url 'my_shop' %}">我的店铺</a></li>
</ul>
{% endblock %}

eshop/templates/customer/remittance.html
{% extends 'customer/homepage.html' %}
{% load bootstrap3 %}

{% block homepage_content %}
<h3>订单详情</h3>
<h4>店铺: <a href = "{% url 'shop' remittance.shop.id %}">{{remittance.shop.name}}</a></h4>
<table class="table">
    <tbody>       
        {% for item in remittance.remittance_items.all %}
        <tr>
            <td>
                商品：<a href = "{% url 'goods' item.goods.shop.id item.goods.id %}">{{ item.goods.name }}</a>
            </td>
            <td>
                <p>数量：{{ item.number }}</p>
            </td>
            <td>
                <p>价格：¥{{ item.goods.price }} * {{item.number}}</p>
            </td>
        <tr>
        {% if remittance.status == 'e' %}
        <tr>
            <td>
                <p>评分：{{item.comment.score}}</p>
            </td>
            <td>
                <p>评价：{{item.comment.content}}</p>
            </td>
        </tr>
        {% endif %}
        {% endfor %}
        <tr>
        <td></td><td></td><td>总价：¥{{remittance.price}}</td>
        </tr>
    </tbody>
</table>

<h4>详细信息</h4>
<table class="table">
    <tbody> 
        <tr><td>订单状态：{{remittance.get_status_display}}</td></tr>
        <tr><td>联系方式：{{remittance.phone}}</td></tr>
        <tr><td>支付方式：{{remittance.get_payment_display}}</td></tr>
        <tr><td>地址：{{remittance.address}}</td></tr>
        <tr><td>留言：{{remittance.message}}</td></tr>
    </tbody>
</table>

{% if remittance.status == 't' %}
    <form method="post" action="{% url 'customer_confirm_remittance' remittance.id %}" >
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">
    确认收货
    </button>
{% elif remittance.status == 'r'%}
    <form method="post" action="{% url 'evaluate_remittance' remittance.id %}" >
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">
    评价商品
    </button>
{% endif %}

{% endblock %}

eshop/templates/customer/remittances.html
{% extends 'customer/homepage.html' %} {% load bootstrap3 %} {% block homepage_content %}
<ul id="myTab" class="nav nav-tabs">
    <li class="active">
        <a href="#all" data-toggle="tab">
             所有订单
        </a>
    </li>
    <li><a href="#finished" data-toggle="tab">已完成订单</a></li>
    <li><a href="#to_receive" data-toggle="tab">待收货订单</a></li>
    <li><a href="#to_evaluate" data-toggle="tab">待评价订单</a></li>    
</ul>
<div id="myTabContent" class="tab-content">
    <div class="tab-pane fade in active" id="all">
        <table class="table">
            <tbody>
            {% for remittance in remittances %}
                <tr>
                    <td><a href="{% url 'remittance' remittance.id %}">订单{{remittance.id}}</a></td>
                    <td>{{remittance.get_status_display}}
                    <td>总价：¥{{remittance.price}}</td>
                    <td>时间：{{remittance.created_at}}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="tab-pane fade" id="finished">
        <table class="table">
            <tbody>
            {% for remittance in remittances %}
            {% if remittance.status == 'e' %}
                <tr>
                    <td><a href="{% url 'remittance' remittance.id %}">订单{{remittance.id}}</a></td>
                    <td>{{remittance.get_status_display}}
                    <td>总价：¥{{remittance.price}}</td>
                    <td>时间：{{remittance.created_at}}</td>
                </tr>
            {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="tab-pane fade" id="to_receive">
        <table class="table">
            <tbody>
            {% for remittance in remittances %}
            {% if remittance.status == 't' %}
                <tr>
                    <td><a href="{% url 'remittance' remittance.id %}">订单{{remittance.id}}</a></td>
                    <td>{{remittance.get_status_display}}
                    <td>总价：¥{{remittance.price}}</td>
                    <td>时间：{{remittance.created_at}}</td>
                </tr>
            {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>
    
    <div class="tab-pane fade" id="to_evaluate">
        <table class="table">
            <tbody>
            {% for remittance in remittances %}
            {% if remittance.status == 'r' %}
                <tr>
                    <td><a href="{% url 'remittance' remittance.id %}">订单{{remittance.id}}</a></td>
                    <td>{{remittance.get_status_display}}
                    <td>总价：¥{{remittance.price}}</td>
                    <td>时间：{{remittance.created_at}}</td>
                </tr>
            {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}